api:
  - any: ["packages/frontend/src/ts/ape/**/*", "packages/backend/src/api/**/*"]

assets:
  - any: ["packages/frontend/static/**/*"]
    all: ["!packages/frontend/static/**/*.html"]

backend:
  - any: ["packages/backend/**/*"]

docs:
  - any: ["**/*.md"]

frontend:
  - any: ["packages/frontend/**/*"]

local dev:
  - any: ["**/gulpfile.js", "**/tsconfig.json"]
